### ISSUE TITLE
DRO in metric or imperial?

### ISSUE THREAD

**Issue by moose4621** [UnfinishedBusiness/ncPilot#4]
I loaded a .nc file that was about 50mm square but when I jogged around it, the dro only moved a couple of whole numbers so I am guessing the DRO is in inches?
If so, can it be changed to metric?

**Comment by UnfinishedBusiness** [comment]
So for simplicity sake I decided to leave things in whatever units the scale is set too. So set your step scale’s to steps per inch if you want to run your machine in inch units or set your step scale’s to steps per mm. I prefer inches so I always set my machines up that way. Beware that if you set your machine up in inch scale to make sure your post processor doesn’t set a G20 because it would be in G21 by default and if a G20 is set the scale would be multiplied by 25.4... I decided to go this route because it kept from having to handle DRO scale changes when switching between G20 and G21 which really isn’t that common, usually people prefer one or another...
