### ISSUE TITLE
cannot find -lfreeglut_static: No such file or directory

### ISSUE THREAD

**Issue by rlwoodjr** [UnfinishedBusiness/ncPilot#9]
When I compile I get this error

```
Linking: bin/release/ncPilot
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lfreeglut_static: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make[1]: *** [Makefile:228: bin/release/ncPilot] Error 1
mingw32-make: *** [Makefile:171: release] Error 2
```

If I delete the -lfreeglut_static from the make file it will create the window exe file, but I a not sure that it good idea

Any help would be appreciated

**Comment by UnfinishedBusiness** [comment]
The windows build is currently broken due to changes on mingw64's side. If it compiles and executes, then run it.

I've sold the rights to ncPilot to an Australian company called [Promach](https://promach.com.au) and they'll be tailoring it to their needs but it won't be open source. What I have here will be available but archived and I'm no longer developing it as I'm working on a more advanced system that will far outperform this system in just about every way.

**Comment by rlwoodjr** [comment]
It compiles and I can jog all axes, so I will go with it.  Thanks for the response.   Nice work.  It is taking some time to see what does what, but I enjoy the challange.
